apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: painters.painter.artists
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: painter.artists
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                style:
                  type: string
                century:
                  type: integer
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: painters
    # singular name to be used as an alias on the CLI and for display
    singular: painter
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Painter
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - pt
---
apiVersion: "painter.artists/v1"
kind: Painter
metadata:
  name: artist-template-1
spec:
  name: pollock
  style: expressionism
  century: 20 
---
apiVersion: "painter.artists/v1"
kind: Painter
metadata:
  name: artist-template-2
spec:
  name: miro
  style: surrealism
  century: 20 
---
apiVersion: "painter.artists/v1"
kind: Painter
metadata:
  name: artist-template-3
spec:
  name: velasquez
  style: baroque
  century: 17
